/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <android/log.h>
#include "opensl.h"
/* Header for class com_hyman_audiodemo_NativeAudio */

#define LOG(...) __android_log_print(ANDROID_LOG_DEBUG, "AudioDemo-JNI", __VA_ARGS__)

#define SAMPLE_RATE 44100
#define CHANNELS 1
#define PERIOD_TIME 20 //ms
#define FRAME_SIZE SAMPLE_RATE*PERIOD_TIME/1000
#define BUFFER_SIZE FRAME_SIZE*CHANNELS
#define TEST_CAPTURE_FILE_PATH "/sdcard/audio.pcm"

static volatile int g_loop_exit = 0;

#ifndef _Included_com_hyman_audiodemo_NativeAudio
#define _Included_com_hyman_audiodemo_NativeAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hyman_audiodemo_NativeAudio
 * Method:    nativeStartCapture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_hyman_audiodemo_NativeAudio_nativeStartCapture
  (JNIEnv *, jobject);

/*
 * Class:     com_hyman_audiodemo_NativeAudio
 * Method:    nativeStopCapture
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_hyman_audiodemo_NativeAudio_nativeStopCapture
  (JNIEnv *, jobject);

/*
 * Class:     com_hyman_audiodemo_NativeAudio
 * Method:    nativeStartPlayback
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_hyman_audiodemo_NativeAudio_nativeStartPlayback
  (JNIEnv *, jobject);

/*
 * Class:     com_hyman_audiodemo_NativeAudio
 * Method:    nativeStopPlayback
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_hyman_audiodemo_NativeAudio_nativeStopPlayback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
